//Maya Preference 2016 (Release 1)
//
//

nameCommand
	-annotation "FumeFX luncher"
	-sourceType "mel"
	-command ("ffxFumeHotkeyLuncher")
	fumeLunchShortcut;

nameCommand
	-annotation "HypershadeWindowNameCommand"
	-sourceType "mel"
	-command ("HypershadeWindow")
	HypershadeWindowNameCommand;

nameCommand
	-annotation "TextureViewWindowNameCommand"
	-sourceType "mel"
	-command ("TextureViewWindow")
	TextureViewWindowNameCommand;

